# Generated by Django 5.2.2 on 2025-06-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
